jobs:
  - template: cicd/templates/build-android.yml
    parameters:
      displayName: 'EducationAndroid'
      workingDirectory: 'education_Android/AgoraEducation'
  - template: cicd/templates/build-ios.yml
    parameters:
      devDisplayName: 'AgoraEducationDEV'
      qaDisplayName: 'AgoraEducationQA'
      workingDirectory: 'education_iOS'
      scheme: 'AgoraEducation'
